# permissions for end users to edit xjoinsynchronizers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: xjoinsynchronizer-editor-role
rules:
- apiGroups:
  - xjoin.cloud.redhat.com
  resources:
  - xjoinsynchronizers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - xjoin.cloud.redhat.com
  resources:
  - xjoinsynchronizers/status
  verbs:
  - get
