apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
    operators.operatorframework.io/builder: operator-sdk-v1.12.0
    operators.operatorframework.io/project_layout: go.kubebuilder.io/v2
  name: xjoin-operator.v0.0.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - displayName: XJoin Data Source Synchronizer
      kind: XJoinDataSourceSynchronizer
      name: xjoindatasourcesynchronizers.xjoin.cloud.redhat.com
      version: v1alpha1
    - displayName: XJoin Data Source
      kind: XJoinDataSource
      name: xjoindatasources.xjoin.cloud.redhat.com
      version: v1alpha1
    - description: XJoinSynchronizer is the Schema for the xjoinsynchronizers API
      displayName: XJoin Synchronizer
      kind: XJoinSynchronizer
      name: xjoinsynchronizers.xjoin.cloud.redhat.com
      version: v1alpha1
  description: XJoin Operator to manage XJoin synchronizers.
  displayName: xjoin-operator
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: true
    type: OwnNamespace
  - supported: true
    type: SingleNamespace
  - supported: true
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - xjoin
  links:
  - name: Xjoin Operator
    url: https://xjoin-operator.domain
  maintainers:
  - email: ckyrouac@redhat.com
    name: Chris Kyrouac
  maturity: alpha
  provider:
    name: Red Hat
    url: https://github.com/redhatinsights/xjoin-operator
  version: 0.0.0
