apiVersion: v1
kind: Template
metadata:
  name: xjoin-operator

parameters:
  - name: VALIDATION_THRESHOLD
    value: "5"
  - name: KAFKA_CLUSTER_NAMESPACE
    value: "platform-mq-stage"
  - name: CONNECT_CLUSTER_NAMESPACE
    value: "xjoin-stage"
  - name: CONNECT_CLUSTER
    value: "xjoin-kafka-connect-strimzi"
  - name: KAFKA_CLUSTER
    value: "platform-mq"
  - name: MANAGED_KAFKA
    value: "false"
  - name: MANAGED_KAFKA_SECRET_NAME
    value: "stage-managed-kafka"
  - name: MANAGED_KAFKA_SECRET_NAMESPACE
    value: "xjoin-operator-stage"
  - name: SCHEMA_REGISTRY_SECRET_NAME
    value: "service-registry-stage"

objects:
  - apiVersion: xjoin.cloud.redhat.com/v1alpha1
    kind: XJoinSynchronizer
    metadata:
      name: xjoinsynchronizer
    spec:
      validationThreshold: ${{VALIDATION_THRESHOLD}}
      kafkaClusterNamespace: ${{KAFKA_CLUSTER_NAMESPACE}}
      connectClusterNamespace: ${{CONNECT_CLUSTER_NAMESPACE}}
      connectCluster: ${{CONNECT_CLUSTER}}
      kafkaCluster: ${{KAFKA_CLUSTER}}
      pause: false
      managedKafka: ${{MANAGED_KAFKA}}
      managedKafkaSecretName: ${{MANAGED_KAFKA_SECRET_NAME}}
      managedKafkaSecretNamespace: ${{MANAGED_KAFKA_SECRET_NAMESPACE}}
      schemaRegistrySecretName: ${{SCHEMA_REGISTRY_SECRET_NAME}}
