//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*


Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CustomSubgraphImage) DeepCopyInto(out *CustomSubgraphImage) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CustomSubgraphImage.
func (in *CustomSubgraphImage) DeepCopy() *CustomSubgraphImage {
	if in == nil {
		return nil
	}
	out := new(CustomSubgraphImage)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretKeyRef) DeepCopyInto(out *SecretKeyRef) {
	*out = *in
	if in.SecretKeyRef != nil {
		in, out := &in.SecretKeyRef, &out.SecretKeyRef
		*out = new(v1.SecretKeySelector)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretKeyRef.
func (in *SecretKeyRef) DeepCopy() *SecretKeyRef {
	if in == nil {
		return nil
	}
	out := new(SecretKeyRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StringOrSecretParameter) DeepCopyInto(out *StringOrSecretParameter) {
	*out = *in
	if in.ValueFrom != nil {
		in, out := &in.ValueFrom, &out.ValueFrom
		*out = new(SecretKeyRef)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StringOrSecretParameter.
func (in *StringOrSecretParameter) DeepCopy() *StringOrSecretParameter {
	if in == nil {
		return nil
	}
	out := new(StringOrSecretParameter)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *XJoinDataSource) DeepCopyInto(out *XJoinDataSource) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new XJoinDataSource.
func (in *XJoinDataSource) DeepCopy() *XJoinDataSource {
	if in == nil {
		return nil
	}
	out := new(XJoinDataSource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *XJoinDataSource) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *XJoinDataSourceList) DeepCopyInto(out *XJoinDataSourceList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]XJoinDataSource, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new XJoinDataSourceList.
func (in *XJoinDataSourceList) DeepCopy() *XJoinDataSourceList {
	if in == nil {
		return nil
	}
	out := new(XJoinDataSourceList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *XJoinDataSourceList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *XJoinDataSourceSynchronizer) DeepCopyInto(out *XJoinDataSourceSynchronizer) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new XJoinDataSourceSynchronizer.
func (in *XJoinDataSourceSynchronizer) DeepCopy() *XJoinDataSourceSynchronizer {
	if in == nil {
		return nil
	}
	out := new(XJoinDataSourceSynchronizer)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *XJoinDataSourceSynchronizer) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *XJoinDataSourceSynchronizerList) DeepCopyInto(out *XJoinDataSourceSynchronizerList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]XJoinDataSourceSynchronizer, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new XJoinDataSourceSynchronizerList.
func (in *XJoinDataSourceSynchronizerList) DeepCopy() *XJoinDataSourceSynchronizerList {
	if in == nil {
		return nil
	}
	out := new(XJoinDataSourceSynchronizerList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *XJoinDataSourceSynchronizerList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *XJoinDataSourceSynchronizerSpec) DeepCopyInto(out *XJoinDataSourceSynchronizerSpec) {
	*out = *in
	if in.DatabaseHostname != nil {
		in, out := &in.DatabaseHostname, &out.DatabaseHostname
		*out = new(StringOrSecretParameter)
		(*in).DeepCopyInto(*out)
	}
	if in.DatabasePort != nil {
		in, out := &in.DatabasePort, &out.DatabasePort
		*out = new(StringOrSecretParameter)
		(*in).DeepCopyInto(*out)
	}
	if in.DatabaseUsername != nil {
		in, out := &in.DatabaseUsername, &out.DatabaseUsername
		*out = new(StringOrSecretParameter)
		(*in).DeepCopyInto(*out)
	}
	if in.DatabasePassword != nil {
		in, out := &in.DatabasePassword, &out.DatabasePassword
		*out = new(StringOrSecretParameter)
		(*in).DeepCopyInto(*out)
	}
	if in.DatabaseName != nil {
		in, out := &in.DatabaseName, &out.DatabaseName
		*out = new(StringOrSecretParameter)
		(*in).DeepCopyInto(*out)
	}
	if in.DatabaseTable != nil {
		in, out := &in.DatabaseTable, &out.DatabaseTable
		*out = new(StringOrSecretParameter)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new XJoinDataSourceSynchronizerSpec.
func (in *XJoinDataSourceSynchronizerSpec) DeepCopy() *XJoinDataSourceSynchronizerSpec {
	if in == nil {
		return nil
	}
	out := new(XJoinDataSourceSynchronizerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *XJoinDataSourceSynchronizerStatus) DeepCopyInto(out *XJoinDataSourceSynchronizerStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new XJoinDataSourceSynchronizerStatus.
func (in *XJoinDataSourceSynchronizerStatus) DeepCopy() *XJoinDataSourceSynchronizerStatus {
	if in == nil {
		return nil
	}
	out := new(XJoinDataSourceSynchronizerStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *XJoinDataSourceSpec) DeepCopyInto(out *XJoinDataSourceSpec) {
	*out = *in
	if in.DatabaseHostname != nil {
		in, out := &in.DatabaseHostname, &out.DatabaseHostname
		*out = new(StringOrSecretParameter)
		(*in).DeepCopyInto(*out)
	}
	if in.DatabasePort != nil {
		in, out := &in.DatabasePort, &out.DatabasePort
		*out = new(StringOrSecretParameter)
		(*in).DeepCopyInto(*out)
	}
	if in.DatabaseUsername != nil {
		in, out := &in.DatabaseUsername, &out.DatabaseUsername
		*out = new(StringOrSecretParameter)
		(*in).DeepCopyInto(*out)
	}
	if in.DatabasePassword != nil {
		in, out := &in.DatabasePassword, &out.DatabasePassword
		*out = new(StringOrSecretParameter)
		(*in).DeepCopyInto(*out)
	}
	if in.DatabaseName != nil {
		in, out := &in.DatabaseName, &out.DatabaseName
		*out = new(StringOrSecretParameter)
		(*in).DeepCopyInto(*out)
	}
	if in.DatabaseTable != nil {
		in, out := &in.DatabaseTable, &out.DatabaseTable
		*out = new(StringOrSecretParameter)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new XJoinDataSourceSpec.
func (in *XJoinDataSourceSpec) DeepCopy() *XJoinDataSourceSpec {
	if in == nil {
		return nil
	}
	out := new(XJoinDataSourceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *XJoinDataSourceStatus) DeepCopyInto(out *XJoinDataSourceStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new XJoinDataSourceStatus.
func (in *XJoinDataSourceStatus) DeepCopy() *XJoinDataSourceStatus {
	if in == nil {
		return nil
	}
	out := new(XJoinDataSourceStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *XJoinIndex) DeepCopyInto(out *XJoinIndex) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new XJoinIndex.
func (in *XJoinIndex) DeepCopy() *XJoinIndex {
	if in == nil {
		return nil
	}
	out := new(XJoinIndex)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *XJoinIndex) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *XJoinIndexList) DeepCopyInto(out *XJoinIndexList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]XJoinIndex, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new XJoinIndexList.
func (in *XJoinIndexList) DeepCopy() *XJoinIndexList {
	if in == nil {
		return nil
	}
	out := new(XJoinIndexList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *XJoinIndexList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *XJoinIndexSynchronizer) DeepCopyInto(out *XJoinIndexSynchronizer) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new XJoinIndexSynchronizer.
func (in *XJoinIndexSynchronizer) DeepCopy() *XJoinIndexSynchronizer {
	if in == nil {
		return nil
	}
	out := new(XJoinIndexSynchronizer)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *XJoinIndexSynchronizer) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *XJoinIndexSynchronizerList) DeepCopyInto(out *XJoinIndexSynchronizerList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]XJoinIndexSynchronizer, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new XJoinIndexSynchronizerList.
func (in *XJoinIndexSynchronizerList) DeepCopy() *XJoinIndexSynchronizerList {
	if in == nil {
		return nil
	}
	out := new(XJoinIndexSynchronizerList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *XJoinIndexSynchronizerList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *XJoinIndexSynchronizerSpec) DeepCopyInto(out *XJoinIndexSynchronizerSpec) {
	*out = *in
	if in.CustomSubgraphImages != nil {
		in, out := &in.CustomSubgraphImages, &out.CustomSubgraphImages
		*out = make([]CustomSubgraphImage, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new XJoinIndexSynchronizerSpec.
func (in *XJoinIndexSynchronizerSpec) DeepCopy() *XJoinIndexSynchronizerSpec {
	if in == nil {
		return nil
	}
	out := new(XJoinIndexSynchronizerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *XJoinIndexSynchronizerStatus) DeepCopyInto(out *XJoinIndexSynchronizerStatus) {
	*out = *in
	in.ValidationResponse.DeepCopyInto(&out.ValidationResponse)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new XJoinIndexSynchronizerStatus.
func (in *XJoinIndexSynchronizerStatus) DeepCopy() *XJoinIndexSynchronizerStatus {
	if in == nil {
		return nil
	}
	out := new(XJoinIndexSynchronizerStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *XJoinIndexSpec) DeepCopyInto(out *XJoinIndexSpec) {
	*out = *in
	if in.CustomSubgraphImages != nil {
		in, out := &in.CustomSubgraphImages, &out.CustomSubgraphImages
		*out = make([]CustomSubgraphImage, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new XJoinIndexSpec.
func (in *XJoinIndexSpec) DeepCopy() *XJoinIndexSpec {
	if in == nil {
		return nil
	}
	out := new(XJoinIndexSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *XJoinIndexStatus) DeepCopyInto(out *XJoinIndexStatus) {
	*out = *in
	if in.DataSources != nil {
		in, out := &in.DataSources, &out.DataSources
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new XJoinIndexStatus.
func (in *XJoinIndexStatus) DeepCopy() *XJoinIndexStatus {
	if in == nil {
		return nil
	}
	out := new(XJoinIndexStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *XJoinIndexValidator) DeepCopyInto(out *XJoinIndexValidator) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new XJoinIndexValidator.
func (in *XJoinIndexValidator) DeepCopy() *XJoinIndexValidator {
	if in == nil {
		return nil
	}
	out := new(XJoinIndexValidator)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *XJoinIndexValidator) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *XJoinIndexValidatorList) DeepCopyInto(out *XJoinIndexValidatorList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]XJoinIndexValidator, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new XJoinIndexValidatorList.
func (in *XJoinIndexValidatorList) DeepCopy() *XJoinIndexValidatorList {
	if in == nil {
		return nil
	}
	out := new(XJoinIndexValidatorList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *XJoinIndexValidatorList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *XJoinIndexValidatorSpec) DeepCopyInto(out *XJoinIndexValidatorSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new XJoinIndexValidatorSpec.
func (in *XJoinIndexValidatorSpec) DeepCopy() *XJoinIndexValidatorSpec {
	if in == nil {
		return nil
	}
	out := new(XJoinIndexValidatorSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *XJoinIndexValidatorStatus) DeepCopyInto(out *XJoinIndexValidatorStatus) {
	*out = *in
	in.ValidationResponse.DeepCopyInto(&out.ValidationResponse)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new XJoinIndexValidatorStatus.
func (in *XJoinIndexValidatorStatus) DeepCopy() *XJoinIndexValidatorStatus {
	if in == nil {
		return nil
	}
	out := new(XJoinIndexValidatorStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *XJoinSynchronizer) DeepCopyInto(out *XJoinSynchronizer) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new XJoinSynchronizer.
func (in *XJoinSynchronizer) DeepCopy() *XJoinSynchronizer {
	if in == nil {
		return nil
	}
	out := new(XJoinSynchronizer)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *XJoinSynchronizer) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *XJoinSynchronizerList) DeepCopyInto(out *XJoinSynchronizerList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]XJoinSynchronizer, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new XJoinSynchronizerList.
func (in *XJoinSynchronizerList) DeepCopy() *XJoinSynchronizerList {
	if in == nil {
		return nil
	}
	out := new(XJoinSynchronizerList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *XJoinSynchronizerList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *XJoinSynchronizerSpec) DeepCopyInto(out *XJoinSynchronizerSpec) {
	*out = *in
	if in.ResourceNamePrefix != nil {
		in, out := &in.ResourceNamePrefix, &out.ResourceNamePrefix
		*out = new(string)
		**out = **in
	}
	if in.KafkaCluster != nil {
		in, out := &in.KafkaCluster, &out.KafkaCluster
		*out = new(string)
		**out = **in
	}
	if in.KafkaClusterNamespace != nil {
		in, out := &in.KafkaClusterNamespace, &out.KafkaClusterNamespace
		*out = new(string)
		**out = **in
	}
	if in.ConnectCluster != nil {
		in, out := &in.ConnectCluster, &out.ConnectCluster
		*out = new(string)
		**out = **in
	}
	if in.ConnectClusterNamespace != nil {
		in, out := &in.ConnectClusterNamespace, &out.ConnectClusterNamespace
		*out = new(string)
		**out = **in
	}
	if in.HBIDBSecretName != nil {
		in, out := &in.HBIDBSecretName, &out.HBIDBSecretName
		*out = new(string)
		**out = **in
	}
	if in.ElasticSearchSecretName != nil {
		in, out := &in.ElasticSearchSecretName, &out.ElasticSearchSecretName
		*out = new(string)
		**out = **in
	}
	if in.ElasticSearchNamespace != nil {
		in, out := &in.ElasticSearchNamespace, &out.ElasticSearchNamespace
		*out = new(string)
		**out = **in
	}
	if in.ElasticSearchIndexTemplate != nil {
		in, out := &in.ElasticSearchIndexTemplate, &out.ElasticSearchIndexTemplate
		*out = new(string)
		**out = **in
	}
	if in.ManagedKafkaSecretName != nil {
		in, out := &in.ManagedKafkaSecretName, &out.ManagedKafkaSecretName
		*out = new(string)
		**out = **in
	}
	if in.ManagedKafkaSecretNamespace != nil {
		in, out := &in.ManagedKafkaSecretNamespace, &out.ManagedKafkaSecretNamespace
		*out = new(string)
		**out = **in
	}
	if in.SchemaRegistrySecretName != nil {
		in, out := &in.SchemaRegistrySecretName, &out.SchemaRegistrySecretName
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new XJoinSynchronizerSpec.
func (in *XJoinSynchronizerSpec) DeepCopy() *XJoinSynchronizerSpec {
	if in == nil {
		return nil
	}
	out := new(XJoinSynchronizerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *XJoinSynchronizerStatus) DeepCopyInto(out *XJoinSynchronizerStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new XJoinSynchronizerStatus.
func (in *XJoinSynchronizerStatus) DeepCopy() *XJoinSynchronizerStatus {
	if in == nil {
		return nil
	}
	out := new(XJoinSynchronizerStatus)
	in.DeepCopyInto(out)
	return out
}
